// Generates lib/qa/widget_index.g.dart: every class declared under lib/ with
// its file and line. The QA harness uses it to point layout findings at
// source, because web builds don't support widget creation tracking.
//
// Run from the repo root:  dart run tool/gen_qa_widget_index.dart
// The Railway QA build (deploy/webapp/Dockerfile) runs it before compiling.

import 'dart:io';

void main() {
  final classDecl = RegExp(r'^\s*(?:abstract\s+|base\s+|final\s+|sealed\s+)*class\s+(\w+)');
  final index = <String, List<String>>{};
  final files = Directory('lib')
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart') && !f.path.endsWith('.g.dart'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final file in files) {
    final path = file.path.replaceAll(r'\', '/');
    final lines = file.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      final match = classDecl.firstMatch(lines[i]);
      if (match != null) {
        index.putIfAbsent(match.group(1)!, () => []).add('$path:${i + 1}');
      }
    }
  }

  String quote(String s) => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";
  final names = index.keys.toList()..sort();
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_qa_widget_index.dart. Do not edit by hand.')
    ..writeln('// Class name -> declaration(s) as "lib/path.dart:line".')
    ..writeln()
    ..writeln('const Map<String, String> qaWidgetIndex = {');
  for (final name in names) {
    out.writeln('  ${quote(name)}: ${quote(index[name]!.join(' | '))},');
  }
  out.writeln('};');
  File('lib/qa/widget_index.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('qaWidgetIndex: ${names.length} classes from ${files.length} files');
}
